version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    image: updatedems-frontend
    container_name: frontend-container
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile.backend
    image: updatedems-backend
    container_name: backend-container
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=3000
